### ISSUE TITLE
Question : why is that not a fork ?

### ISSUE THREAD

**Issue by Zekirax** [RaphaelIT7/sourcesdk-gmod#1]
You could improve the actual source SDK minimal. Can you explain the reason?

**Comment by RaphaelIT7** [comment]
I did this because I wanted to first finish this and then create a fork and pr with 1 commit instead of like +100.
When this is finished, I will create a fork and PR and then archive(or remove) this repo and link to the original sourcesdk-minimal and the pr.

**Comment by Zekirax** [comment]
Ok thanks.
